[package]
name = "code-edit"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.0"
uuid = { version = "1", features = ["v4", "serde"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4"
env_logger = "0.11.5"
