name: Build Rust Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        # os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: binary-linux
            binary_path: ./target/x86_64-unknown-linux-musl/release/code-edit
            upload_name: code-edit-linux
          # - os: windows-latest
          #   artifact_name: binary-windows
          #   binary_path: ./target/release/code-edit.exe
          #   upload_name: code-edit-windows.exe
          - os: macos-latest
            artifact_name: binary-macos
            binary_path: ./target/release/code-edit
            upload_name: code-edit-macos

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Install cross
      if: matrix.os == 'ubuntu-latest'
      run: cargo install cross

    - name: Build for ${{ matrix.os }}
      if: matrix.os == 'windows-latest' || matrix.os == 'macos-latest'
      run: cargo build --release

    - name: Build for ${{ matrix.os }}
      if: matrix.os == 'ubuntu-latest'
      run: cross build --release --target x86_64-unknown-linux-musl

    - name: Rename binary
      run: mv ${{ matrix.binary_path }} ${{ matrix.upload_name }}

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: ${{ matrix.upload_name }}
        generate_release_notes: true
