name: Build Rust Binary

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
          - os: ubuntu-latest
            artifact_name: binary-linux
            binary_path: ./target/release/code-edit
          - os: windows-latest
            artifact_name: binary-windows
            binary_path: ./target/release/code-edit.exe
          - os: macos-latest
            artifact_name: binary-macos
            binary_path: ./target/release/code-edit

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: stable

    - name: Build
      run: cargo build --release

    - name: Upload binary to artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact_name }}
        path: ${{ matrix.binary_path }}
